"""empty message

Revision ID: d5e8a4eb59ea
Revises: f84fb3e81187
Create Date: 2023-07-30 22:24:57.675201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5e8a4eb59ea'
down_revision = 'f84fb3e81187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('create_at')
        batch_op.drop_column('update_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('create_at', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
